import { Tag } from './TagSelector';

export const sampleTagData: Tag[] = [
  // ========== SHOTS: DISTANCE & SIZE (10 tags) ==========
  {
    id: 'sd1',
    name: 'Extreme Wide Shot',
    category: 'Shots',
    promptKeyword: 'extreme wide shot, vast landscape, epic scale, subject barely visible',
    color: '#3B82F6',
    description: 'Subject extremely small, emphasizing vast environment',
  },
  {
    id: 'sd2',
    name: 'Wide Shot',
    category: 'Shots',
    promptKeyword: 'wide shot, full body with environment, establishing shot',
    color: '#3B82F6',
    description: 'Full subject with significant surrounding context',
  },
  {
    id: 'sd3',
    name: 'Full Shot',
    category: 'Shots',
    promptKeyword: 'full shot, head to toe, complete body framing',
    color: '#3B82F6',
    description: 'Subject from head to toe filling frame',
  },
  {
    id: 'sd4',
    name: 'Medium Long Shot',
    category: 'Shots',
    promptKeyword: 'medium long shot, knees up, 3/4 shot, american shot',
    color: '#3B82F6',
    description: 'Subject from knees up, balanced framing',
  },
  {
    id: 'sd5',
    name: 'Cowboy Shot',
    category: 'Shots',
    promptKeyword: 'cowboy shot, mid-thighs up, hero framing',
    color: '#3B82F6',
    description: 'From mid-thighs up, powerful framing',
  },
  {
    id: 'sd6',
    name: 'Medium Shot',
    category: 'Shots',
    promptKeyword: 'medium shot, waist up, conversational framing',
    color: '#3B82F6',
    description: 'Waist up, most versatile shot type',
  },
  {
    id: 'sd7',
    name: 'Medium Close-Up',
    category: 'Shots',
    promptKeyword: 'medium close-up, chest up, shoulders framing',
    color: '#3B82F6',
    description: 'Chest/shoulders up, emphasis on face',
  },
  {
    id: 'sd8',
    name: 'Close-Up',
    category: 'Shots',
    promptKeyword: 'close-up, face only, emotional detail',
    color: '#3B82F6',
    description: 'Head and neck only, high intimacy',
  },
  {
    id: 'sd9',
    name: 'Extreme Close-Up',
    category: 'Shots',
    promptKeyword: 'extreme close-up, single feature, magnified detail',
    color: '#3B82F6',
    description: 'Single facial feature or small detail',
  },
  {
    id: 'sd10',
    name: 'Macro Shot',
    category: 'Shots',
    promptKeyword: 'macro shot, microscopic detail, extreme magnification, texture',
    color: '#3B82F6',
    description: 'Microscopic level detail and texture',
  },

  // ========== SHOTS: ANGLES (10 tags) ==========
  {
    id: 'sa1',
    name: 'Eye-Level',
    category: 'Shots',
    promptKeyword: 'eye-level angle, neutral perspective, straight-on',
    color: '#60A5FA',
    description: 'Camera at subject eye height, neutral',
  },
  {
    id: 'sa2',
    name: 'Low Angle',
    category: 'Shots',
    promptKeyword: 'low angle, looking up, powerful perspective',
    color: '#60A5FA',
    description: 'Camera below subject, empowering',
  },
  {
    id: 'sa3',
    name: 'High Angle',
    category: 'Shots',
    promptKeyword: 'high angle, looking down, diminishing perspective',
    color: '#60A5FA',
    description: 'Camera above subject, vulnerable feel',
  },
  {
    id: 'sa4',
    name: 'Overhead',
    category: 'Shots',
    promptKeyword: 'overhead shot, birds eye view, top-down perspective',
    color: '#60A5FA',
    description: 'Directly above at 90 degrees',
  },
  {
    id: 'sa5',
    name: "Worm's Eye",
    category: 'Shots',
    promptKeyword: "worm's eye view, ground level looking up, extreme low angle",
    color: '#60A5FA',
    description: 'Extremely low from ground level',
  },
  {
    id: 'sa6',
    name: 'Dutch Angle',
    category: 'Shots',
    promptKeyword: 'dutch angle, tilted camera, diagonal horizon, off-balance',
    color: '#60A5FA',
    description: 'Tilted camera creating unease',
  },
  {
    id: 'sa7',
    name: 'Over-the-Shoulder',
    category: 'Shots',
    promptKeyword: 'over-the-shoulder shot, OTS, dialogue framing',
    color: '#60A5FA',
    description: 'Behind one subject viewing another',
  },
  {
    id: 'sa8',
    name: 'POV',
    category: 'Shots',
    promptKeyword: 'POV shot, first-person perspective, character viewpoint',
    color: '#60A5FA',
    description: 'First-person character perspective',
  },
  {
    id: 'sa9',
    name: 'Selfie Angle',
    category: 'Shots',
    promptKeyword: 'selfie angle, high angle at arms length, casual framing',
    color: '#60A5FA',
    description: 'High angle at arm length, social media style',
  },
  {
    id: 'sa10',
    name: 'Ground Level',
    category: 'Shots',
    promptKeyword: 'ground level shot, floor perspective, low intimate angle',
    color: '#60A5FA',
    description: 'Camera on ground surface',
  },

  // ========== CAMERA MOTION: BASIC (6 tags) ==========
  {
    id: 'cmb1',
    name: 'Static',
    category: 'Camera Motion',
    promptKeyword: 'static camera, locked off, no movement, fixed frame',
    color: '#10B981',
    description: 'No camera movement, stable composition',
  },
  {
    id: 'cmb2',
    name: 'Pan',
    category: 'Camera Motion',
    promptKeyword: 'camera pan, horizontal rotation, sweeping motion',
    color: '#10B981',
    description: 'Horizontal rotation left or right',
  },
  {
    id: 'cmb3',
    name: 'Tilt',
    category: 'Camera Motion',
    promptKeyword: 'camera tilt, vertical rotation, up and down movement',
    color: '#10B981',
    description: 'Vertical rotation up or down',
  },
  {
    id: 'cmb4',
    name: 'Zoom In',
    category: 'Camera Motion',
    promptKeyword: 'zoom in, magnify subject, optical push',
    color: '#10B981',
    description: 'Lens magnification toward subject',
  },
  {
    id: 'cmb5',
    name: 'Zoom Out',
    category: 'Camera Motion',
    promptKeyword: 'zoom out, reveal context, optical pull',
    color: '#10B981',
    description: 'Lens widening to show more',
  },
  {
    id: 'cmb6',
    name: 'Pedestal',
    category: 'Camera Motion',
    promptKeyword: 'pedestal move, vertical camera movement, elevator shot',
    color: '#10B981',
    description: 'Camera moves up or down vertically',
  },

  // ========== CAMERA MOTION: ADVANCED (5 tags) ==========
  {
    id: 'cma1',
    name: 'Dolly In',
    category: 'Camera Motion',
    promptKeyword: 'dolly in, push in, camera moves forward, approaching subject',
    color: '#059669',
    description: 'Camera physically moves toward subject',
  },
  {
    id: 'cma2',
    name: 'Dolly Out',
    category: 'Camera Motion',
    promptKeyword: 'dolly out, pull back, camera moves backward, revealing context',
    color: '#059669',
    description: 'Camera physically moves away from subject',
  },
  {
    id: 'cma3',
    name: 'Truck',
    category: 'Camera Motion',
    promptKeyword: 'truck shot, lateral tracking, sideways camera movement',
    color: '#059669',
    description: 'Camera moves sideways parallel to subject',
  },
  {
    id: 'cma4',
    name: 'Orbit',
    category: 'Camera Motion',
    promptKeyword: 'orbit shot, 360 rotation, circling subject, revolving camera',
    color: '#059669',
    description: 'Camera circles around subject',
  },
  {
    id: 'cma5',
    name: 'Crane',
    category: 'Camera Motion',
    promptKeyword: 'crane shot, sweeping vertical movement, jib arm, aerial perspective',
    color: '#059669',
    description: 'High sweeping movement from crane',
  },

  // ========== CAMERA MOTION: CINEMATIC (7 tags) ==========
  {
    id: 'cmc1',
    name: 'Dolly Zoom',
    category: 'Camera Motion',
    promptKeyword: 'dolly zoom, vertigo effect, background warp, simultaneous dolly and zoom',
    color: '#14B8A6',
    description: 'Dolly + zoom creating vertigo effect',
  },
  {
    id: 'cmc2',
    name: 'Crash Zoom',
    category: 'Camera Motion',
    promptKeyword: 'crash zoom, fast zoom, rapid magnification, aggressive zoom',
    color: '#14B8A6',
    description: 'Extremely fast sudden zoom',
  },
  {
    id: 'cmc3',
    name: 'FPV Drone',
    category: 'Camera Motion',
    promptKeyword: 'FPV drone, fast aerial movement, dynamic flying, racing drone perspective',
    color: '#14B8A6',
    description: 'Fast agile drone racing style',
  },
  {
    id: 'cmc4',
    name: 'Bullet Time',
    category: 'Camera Motion',
    promptKeyword: 'bullet time, frozen time with moving camera, matrix effect, time freeze',
    color: '#14B8A6',
    description: 'Frozen time with camera movement',
  },
  {
    id: 'cmc5',
    name: 'Handheld',
    category: 'Camera Motion',
    promptKeyword: 'handheld camera, natural shake, documentary style, organic movement',
    color: '#14B8A6',
    description: 'Hand-operated with natural shake',
  },
  {
    id: 'cmc6',
    name: 'Roll',
    category: 'Camera Motion',
    promptKeyword: 'camera roll, rotating horizon, spinning perspective, barrel roll',
    color: '#14B8A6',
    description: 'Camera rotates on lens axis',
  },
  {
    id: 'cmc7',
    name: 'Rack Focus',
    category: 'Camera Motion',
    promptKeyword: 'rack focus, focus pull, shift focus, depth of field transition',
    color: '#14B8A6',
    description: 'Focus shifts between depths',
  },

  // ========== LIGHTING (9 tags) ==========
  {
    id: 'l1',
    name: 'Cinematic',
    category: 'Lighting',
    promptKeyword: 'cinematic lighting, dramatic shadows, three-point lighting, film quality',
    color: '#F59E0B',
    description: 'Professional film-style lighting',
  },
  {
    id: 'l2',
    name: 'Natural',
    category: 'Lighting',
    promptKeyword: 'natural lighting, ambient light, realistic illumination, environmental light',
    color: '#F59E0B',
    description: 'Realistic environmental lighting',
  },
  {
    id: 'l3',
    name: 'Studio',
    category: 'Lighting',
    promptKeyword: 'studio lighting, even illumination, controlled lighting, professional setup',
    color: '#F59E0B',
    description: 'Even controlled studio lighting',
  },
  {
    id: 'l4',
    name: 'Neon',
    category: 'Lighting',
    promptKeyword: 'neon lighting, vibrant colors, electric glow, cyberpunk aesthetic',
    color: '#EC4899',
    description: 'Vibrant neon and LED lighting',
  },
  {
    id: 'l5',
    name: 'Golden Hour',
    category: 'Lighting',
    promptKeyword: 'golden hour, warm sunset light, magic hour, amber tones',
    color: '#F59E0B',
    description: 'Warm sunset/sunrise lighting',
  },
  {
    id: 'l6',
    name: 'Dark',
    category: 'Lighting',
    promptKeyword: 'dark lighting, low-key, heavy shadows, minimal illumination',
    color: '#78716C',
    description: 'Low-key with heavy shadows',
  },
  {
    id: 'l7',
    name: 'Volumetric',
    category: 'Lighting',
    promptKeyword: 'volumetric lighting, god rays, light beams, atmospheric lighting',
    color: '#60A5FA',
    description: 'Visible light beams through atmosphere',
  },
  {
    id: 'l8',
    name: 'Rembrandt',
    category: 'Lighting',
    promptKeyword: 'rembrandt lighting, triangle of light, classic portrait lighting, chiaroscuro',
    color: '#A78BFA',
    description: 'Classic portrait with light triangle',
  },
  {
    id: 'l9',
    name: 'Split Lighting',
    category: 'Lighting',
    promptKeyword: 'split lighting, half face lit, dramatic contrast, divided illumination',
    color: '#EF4444',
    description: 'Half face in light, half in shadow',
  },

  // ========== MOOD (10 tags) ==========
  {
    id: 'm1',
    name: 'Happy',
    category: 'Mood',
    promptKeyword: 'happy, joyful, cheerful, uplifting, positive energy',
    color: '#FBBF24',
    description: 'Bright uplifting atmosphere',
  },
  {
    id: 'm2',
    name: 'Sad',
    category: 'Mood',
    promptKeyword: 'sad, melancholic, somber, emotional, gentle sorrow',
    color: '#6366F1',
    description: 'Melancholic contemplative tone',
  },
  {
    id: 'm3',
    name: 'Tense',
    category: 'Mood',
    promptKeyword: 'tense, suspenseful, anxious, edge of seat, anticipation',
    color: '#EF4444',
    description: 'Anxiety-inducing suspense',
  },
  {
    id: 'm4',
    name: 'Peaceful',
    category: 'Mood',
    promptKeyword: 'peaceful, calm, serene, tranquil, meditative',
    color: '#10B981',
    description: 'Calm serene atmosphere',
  },
  {
    id: 'm5',
    name: 'Energetic',
    category: 'Mood',
    promptKeyword: 'energetic, dynamic, vibrant, lively, spirited',
    color: '#F59E0B',
    description: 'High-energy dynamic tone',
  },
  {
    id: 'm6',
    name: 'Mysterious',
    category: 'Mood',
    promptKeyword: 'mysterious, enigmatic, intriguing, secretive, puzzle-like',
    color: '#8B5CF6',
    description: 'Enigmatic intriguing atmosphere',
  },
  {
    id: 'm7',
    name: 'Romantic',
    category: 'Mood',
    promptKeyword: 'romantic, intimate, affectionate, soft, loving',
    color: '#EC4899',
    description: 'Intimate affectionate atmosphere',
  },
  {
    id: 'm8',
    name: 'Melancholic',
    category: 'Mood',
    promptKeyword: 'melancholic, bittersweet, wistful, nostalgic, poetic sadness',
    color: '#6366F1',
    description: 'Bittersweet nostalgic tone',
  },
  {
    id: 'm9',
    name: 'Euphoric',
    category: 'Mood',
    promptKeyword: 'euphoric, ecstatic, blissful, transcendent, overwhelming joy',
    color: '#A78BFA',
    description: 'Ecstatic elevated atmosphere',
  },
  {
    id: 'm10',
    name: 'Ominous',
    category: 'Mood',
    promptKeyword: 'ominous, foreboding, threatening, sinister, dark premonition',
    color: '#78716C',
    description: 'Foreboding threatening atmosphere',
  },

  // ========== ENERGY (7 tags) ==========
  {
    id: 'e1',
    name: 'Fast-paced Action',
    category: 'Energy',
    promptKeyword: 'fast-paced action, rapid movement, high tempo, kinetic energy, adrenaline',
    color: '#DC2626',
    description: 'Rapid high-tempo movement',
  },
  {
    id: 'e2',
    name: 'Dynamic Motion',
    category: 'Energy',
    promptKeyword: 'dynamic motion, varied movement, flowing action, choreographed',
    color: '#F59E0B',
    description: 'Varied flowing movement',
  },
  {
    id: 'e3',
    name: 'Energetic Movement',
    category: 'Energy',
    promptKeyword: 'energetic movement, lively motion, spirited activity, vibrant',
    color: '#FBBF24',
    description: 'Lively spirited motion',
  },
  {
    id: 'e4',
    name: 'Natural Speed (24fps)',
    category: 'Energy',
    promptKeyword: 'natural speed, 24fps, cinematic frame rate, real-time motion',
    color: '#6366F1',
    description: 'Standard cinematic motion',
  },
  {
    id: 'e5',
    name: 'Slow Motion',
    category: 'Energy',
    promptKeyword: 'slow motion, time slowed, graceful detail, dramatic emphasis',
    color: '#8B5CF6',
    description: 'Slowed time for emphasis',
  },
  {
    id: 'e6',
    name: 'Speed Ramp',
    category: 'Energy',
    promptKeyword: 'speed ramp, variable speed, temporal transition, dynamic pacing',
    color: '#A78BFA',
    description: 'Variable speed transitions',
  },
  {
    id: 'e7',
    name: 'Quick',
    category: 'Energy',
    promptKeyword: 'quick motion, snappy movement, brief action, immediate',
    color: '#EC4899',
    description: 'Brief snappy movement',
  },

  // ========== STYLE (10 tags) ==========
  {
    id: 'st1',
    name: 'Minimalist',
    category: 'Style',
    promptKeyword: 'minimalist, clean, uncluttered, negative space, essential elements',
    color: '#94A3B8',
    description: 'Stripped-down aesthetic focusing on essentials',
  },
  {
    id: 'st2',
    name: 'Simple',
    category: 'Style',
    promptKeyword: 'simple, straightforward, uncomplicated, clear, direct',
    color: '#CBD5E1',
    description: 'Straightforward uncomplicated approach',
  },
  {
    id: 'st3',
    name: 'Detailed',
    category: 'Style',
    promptKeyword: 'detailed, intricate, rich, complex, layered',
    color: '#0891B2',
    description: 'Rich in visual information and complexity',
  },
  {
    id: 'st4',
    name: 'Descriptive',
    category: 'Style',
    promptKeyword: 'descriptive, clear, informative, explanatory, literal',
    color: '#06B6D4',
    description: 'Clear informative visual style',
  },
  {
    id: 'st5',
    name: 'Dynamic',
    category: 'Style',
    promptKeyword: 'dynamic, energetic, movement-focused, active, kinetic',
    color: '#F59E0B',
    description: 'Energetic movement-focused style',
  },
  {
    id: 'st6',
    name: 'Cinematic',
    category: 'Style',
    promptKeyword: 'cinematic, film-quality, dramatic, professional, hollywood',
    color: '#8B5CF6',
    description: 'Film-quality production values',
  },
  {
    id: 'st7',
    name: 'Documentary',
    category: 'Style',
    promptKeyword: 'documentary, observational, realistic, authentic, truthful',
    color: '#78716C',
    description: 'Observational realistic style',
  },
  {
    id: 'st8',
    name: 'Animation',
    category: 'Style',
    promptKeyword: 'animation, stylized, illustrated, artistic, designed',
    color: '#EC4899',
    description: 'Stylized illustrated aesthetic',
  },
  {
    id: 'st9',
    name: 'Action',
    category: 'Style',
    promptKeyword: 'action, fast-paced, kinetic, physical, dynamic',
    color: '#DC2626',
    description: 'Fast-paced kinetic style',
  },
  {
    id: 'st10',
    name: 'Experimental',
    category: 'Style',
    promptKeyword: 'experimental, avant-garde, unconventional, innovative, artistic',
    color: '#A78BFA',
    description: 'Avant-garde unconventional approach',
  },

  // ========== CAMERA DIRECTION: ADVANCED (11 tags) ==========
  {
    id: 'cda1',
    name: 'Orbital Rotation',
    category: 'Camera Direction',
    promptKeyword: 'orbital rotation, 360 circle, revolving around subject',
    color: '#14B8A6',
    description: 'Continuous circle around subject',
  },
  {
    id: 'cda2',
    name: 'Push In',
    category: 'Camera Direction',
    promptKeyword: 'push in, aggressive forward, penetrating movement',
    color: '#14B8A6',
    description: 'Direct forward toward subject',
  },
  {
    id: 'cda3',
    name: 'Pull Out',
    category: 'Camera Direction',
    promptKeyword: 'pull out, reveal context, backward movement',
    color: '#14B8A6',
    description: 'Direct backward from subject',
  },
  {
    id: 'cda4',
    name: 'Track Forward',
    category: 'Camera Direction',
    promptKeyword: 'track forward, following movement, progression',
    color: '#14B8A6',
    description: 'Forward following subject',
  },
  {
    id: 'cda5',
    name: 'Track Backward',
    category: 'Camera Direction',
    promptKeyword: 'track backward, retreating perspective, backing away',
    color: '#14B8A6',
    description: 'Backward while maintaining framing',
  },
  {
    id: 'cda6',
    name: 'Spiral In',
    category: 'Camera Direction',
    promptKeyword: 'spiral in, hypnotic approach, rotating forward',
    color: '#14B8A6',
    description: 'Spiral trajectory toward center',
  },
  {
    id: 'cda7',
    name: 'Spiral Out',
    category: 'Camera Direction',
    promptKeyword: 'spiral out, expanding rotation, rotating backward',
    color: '#14B8A6',
    description: 'Spiral trajectory away from center',
  },
  {
    id: 'cda8',
    name: 'Arc Movement',
    category: 'Camera Direction',
    promptKeyword: 'arc movement, curved path, graceful sweep',
    color: '#14B8A6',
    description: 'Curved path around subject',
  },
  {
    id: 'cda9',
    name: 'Diagonal Traverse',
    category: 'Camera Direction',
    promptKeyword: 'diagonal traverse, angled movement, dynamic path',
    color: '#14B8A6',
    description: 'Diagonal path through space',
  },
  {
    id: 'cda10',
    name: 'Vertical Rise',
    category: 'Camera Direction',
    promptKeyword: 'vertical rise, ascending, upward climb',
    color: '#14B8A6',
    description: 'Straight upward movement',
  },
  {
    id: 'cda11',
    name: 'Vertical Descent',
    category: 'Camera Direction',
    promptKeyword: 'vertical descent, descending, downward fall',
    color: '#14B8A6',
    description: 'Straight downward movement',
  },

  // ========== CAMERA STYLE (19 tags) ==========
  {
    id: 'cs1',
    name: 'Steadicam Flow',
    category: 'Camera Style',
    promptKeyword: 'steadicam, smooth gliding, floating movement, stabilized',
    color: '#6366F1',
    description: 'Ultra-smooth gliding movement',
  },
  {
    id: 'cs2',
    name: 'Drone Aerials',
    category: 'Camera Style',
    promptKeyword: 'drone aerials, aerial perspective, flying camera, overhead',
    color: '#6366F1',
    description: 'Aerial unmanned flying camera',
  },
  {
    id: 'cs3',
    name: 'Handheld Urgency',
    category: 'Camera Style',
    promptKeyword: 'handheld urgency, raw, immediate, shaky, documentary',
    color: '#6366F1',
    description: 'Intentionally unsteady handheld',
  },
  {
    id: 'cs4',
    name: 'Crane Elegance',
    category: 'Camera Style',
    promptKeyword: 'crane elegance, sweeping movement, majestic, grand',
    color: '#6366F1',
    description: 'Sweeping crane movements',
  },
  {
    id: 'cs5',
    name: 'Dolly Precision',
    category: 'Camera Style',
    promptKeyword: 'dolly precision, exact movement, technical, calculated',
    color: '#6366F1',
    description: 'Precise track movements',
  },
  {
    id: 'cs6',
    name: 'VR 360',
    category: 'Camera Style',
    promptKeyword: 'VR 360, spherical capture, omnidirectional, immersive',
    color: '#6366F1',
    description: 'Spherical 360-degree capture',
  },
  {
    id: 'cs7',
    name: 'Multi-angle Rig',
    category: 'Camera Style',
    promptKeyword: 'multi-angle rig, multiple cameras, bullet time, matrix effect',
    color: '#6366F1',
    description: 'Multiple synchronized cameras',
  },
  {
    id: 'cs8',
    name: 'Static Tripod',
    category: 'Camera Style',
    promptKeyword: 'static tripod, locked camera, stable, unchanging frame',
    color: '#6366F1',
    description: 'Completely locked tripod',
  },
  {
    id: 'cs9',
    name: 'Gimbal Smoothness',
    category: 'Camera Style',
    promptKeyword: 'gimbal smooth, electronic stabilization, hybrid movement',
    color: '#6366F1',
    description: 'Electronically stabilized handheld',
  },
  {
    id: 'cs10',
    name: 'Slider Motion',
    category: 'Camera Style',
    promptKeyword: 'slider motion, lateral glide, horizontal track, subtle movement',
    color: '#6366F1',
    description: 'Smooth lateral sliding',
  },
  {
    id: 'cs11',
    name: 'Jib Sweep',
    category: 'Camera Style',
    promptKeyword: 'jib sweep, boom arm, vertical arc, overhead movement',
    color: '#6366F1',
    description: 'Boom arm vertical arcs',
  },
  {
    id: 'cs12',
    name: 'POV Immersion',
    category: 'Camera Style',
    promptKeyword: 'POV immersion, first-person, subjective camera, character eyes',
    color: '#6366F1',
    description: 'First-person perspective',
  },
  {
    id: 'cs13',
    name: 'Time-slice Array',
    category: 'Camera Style',
    promptKeyword: 'time-slice array, freeze rotation, bullet time array',
    color: '#6366F1',
    description: 'Camera array freeze-frame rotation',
  },
  {
    id: 'cs14',
    name: 'Macro Extreme',
    category: 'Camera Style',
    promptKeyword: 'macro extreme, ultra close-up, microscopic detail, magnification',
    color: '#6366F1',
    description: 'Ultra close-up cinematography',
  },
  {
    id: 'cs15',
    name: 'Tilt-shift Miniature',
    category: 'Camera Style',
    promptKeyword: 'tilt-shift miniature, toy-like, selective focus, model appearance',
    color: '#6366F1',
    description: 'Miniature toy-like effect',
  },
  {
    id: 'cs16',
    name: 'Snorricam Character',
    category: 'Camera Style',
    promptKeyword: 'snorricam, body-mounted camera, disorienting, world spinning',
    color: '#6366F1',
    description: 'Camera mounted to subject body',
  },
  {
    id: 'cs17',
    name: 'Whip Pan Dynamics',
    category: 'Camera Style',
    promptKeyword: 'whip pan, fast horizontal pan, motion blur, energetic transition',
    color: '#6366F1',
    description: 'Extremely fast horizontal pan',
  },
  {
    id: 'cs18',
    name: 'Dutch Angle Tension',
    category: 'Camera Style',
    promptKeyword: 'dutch angle tension, tilted horizon, off-kilter, unease',
    color: '#6366F1',
    description: 'Tilted camera creating unease',
  },
  {
    id: 'cs19',
    name: 'Underwater Housing',
    category: 'Camera Style',
    promptKeyword: 'underwater housing, submerged, aquatic perspective, waterproof',
    color: '#6366F1',
    description: 'Underwater cinematography',
  },

  // ========== PACING (19 tags) ==========
  {
    id: 'p1',
    name: 'Slow Burn',
    category: 'Pacing',
    promptKeyword: 'slow burn, gradual build, patient pacing, methodical',
    color: '#7C3AED',
    description: 'Deliberately gradual pacing',
  },
  {
    id: 'p2',
    name: 'Rhythmic Pulse',
    category: 'Pacing',
    promptKeyword: 'rhythmic pulse, beat-driven, metronomic, consistent tempo',
    color: '#7C3AED',
    description: 'Consistent beat-driven rhythm',
  },
  {
    id: 'p3',
    name: 'Frantic Energy',
    category: 'Pacing',
    promptKeyword: 'frantic energy, chaotic, rapid-fire, overwhelming speed',
    color: '#7C3AED',
    description: 'Chaotic rapid-fire pacing',
  },
  {
    id: 'p4',
    name: 'Ebb and Flow',
    category: 'Pacing',
    promptKeyword: 'ebb and flow, alternating pace, rhythmic variation, breathing',
    color: '#7C3AED',
    description: 'Alternating fast and slow',
  },
  {
    id: 'p5',
    name: 'Hypnotic Drift',
    category: 'Pacing',
    promptKeyword: 'hypnotic drift, slow dreamy, trance-like, meditative',
    color: '#7C3AED',
    description: 'Slow dreamy progression',
  },
  {
    id: 'p6',
    name: 'Time-lapse Rush',
    category: 'Pacing',
    promptKeyword: 'time-lapse rush, compressed time, accelerated passage',
    color: '#7C3AED',
    description: 'Compressed time acceleration',
  },
  {
    id: 'p7',
    name: 'Stop-motion Staccato',
    category: 'Pacing',
    promptKeyword: 'stop-motion staccato, jerky, frame-by-frame, choppy',
    color: '#7C3AED',
    description: 'Jerky frame-by-frame aesthetic',
  },
  {
    id: 'p8',
    name: 'Gradual Build',
    category: 'Pacing',
    promptKeyword: 'gradual build, crescendo, increasing intensity, momentum',
    color: '#7C3AED',
    description: 'Steadily increasing pace',
  },
  {
    id: 'p9',
    name: 'Quick Cut Rhythm',
    category: 'Pacing',
    promptKeyword: 'quick cut rhythm, rapid editing, short shots, MTV style',
    color: '#7C3AED',
    description: 'Rapid editing with short shots',
  },
  {
    id: 'p10',
    name: 'Long Take Meditation',
    category: 'Pacing',
    promptKeyword: 'long take meditation, extended shot, uninterrupted, contemplative',
    color: '#7C3AED',
    description: 'Extended uninterrupted shots',
  },
  {
    id: 'p11',
    name: 'Jump Cut Energy',
    category: 'Pacing',
    promptKeyword: 'jump cut energy, jarring cuts, discontinuity, vlog style',
    color: '#7C3AED',
    description: 'Intentional jarring cuts',
  },
  {
    id: 'p12',
    name: 'Match Cut Flow',
    category: 'Pacing',
    promptKeyword: 'match cut flow, seamless transitions, visual rhyming, clever editing',
    color: '#7C3AED',
    description: 'Seamless matching transitions',
  },
  {
    id: 'p13',
    name: 'Cross-dissolve Dreamscape',
    category: 'Pacing',
    promptKeyword: 'cross-dissolve dreamscape, overlapping fades, soft transitions, ethereal',
    color: '#7C3AED',
    description: 'Overlapping soft fades',
  },
  {
    id: 'p14',
    name: 'Parallel Action',
    category: 'Pacing',
    promptKeyword: 'parallel action, cross-cutting, simultaneous events, intercutting',
    color: '#7C3AED',
    description: 'Cross-cutting between events',
  },
  {
    id: 'p15',
    name: 'Slow Motion Impact',
    category: 'Pacing',
    promptKeyword: 'slow motion impact, strategic slowdown, dramatic emphasis',
    color: '#7C3AED',
    description: 'Strategic slow motion emphasis',
  },
  {
    id: 'p16',
    name: 'Ramping Dynamics',
    category: 'Pacing',
    promptKeyword: 'ramping dynamics, variable speed, speed transitions, time manipulation',
    color: '#7C3AED',
    description: 'Variable speed within shot',
  },
  {
    id: 'p17',
    name: 'Montage Tempo',
    category: 'Pacing',
    promptKeyword: 'montage tempo, rapid succession, training sequence, time compression',
    color: '#7C3AED',
    description: 'Rapid succession of shots',
  },
  {
    id: 'p18',
    name: 'Continuous Flow',
    category: 'Pacing',
    promptKeyword: 'continuous flow, seamless progression, no cuts, real-time',
    color: '#7C3AED',
    description: 'Seamless uninterrupted progression',
  },
  {
    id: 'p19',
    name: 'Episodic Breaks',
    category: 'Pacing',
    promptKeyword: 'episodic breaks, chapter structure, act breaks, segments',
    color: '#7C3AED',
    description: 'Clear chapter-like breaks',
  },

  // ========== SPECIAL EFFECTS: PRACTICAL (9 tags) ==========
  {
    id: 'sfp1',
    name: 'Practical Effects',
    category: 'Special Effects',
    promptKeyword: 'practical effects, physical effects, in-camera, tangible, real',
    color: '#F97316',
    description: 'Physical tangible effects on set',
  },
  {
    id: 'sfp2',
    name: 'CGI Enhancement',
    category: 'Special Effects',
    promptKeyword: 'CGI enhancement, computer-generated, digital effects, virtual',
    color: '#F97316',
    description: 'Computer-generated imagery',
  },
  {
    id: 'sfp3',
    name: 'Analog Glitches',
    category: 'Special Effects',
    promptKeyword: 'analog glitches, VHS artifacts, retro distortion, tape errors',
    color: '#F97316',
    description: 'VHS-style retro distortion',
  },
  {
    id: 'sfp4',
    name: 'Light Painting',
    category: 'Special Effects',
    promptKeyword: 'light painting, long exposure, light trails, luminous drawing',
    color: '#F97316',
    description: 'Long exposure light trails',
  },
  {
    id: 'sfp5',
    name: 'Projection Mapping',
    category: 'Special Effects',
    promptKeyword: 'projection mapping, architectural projection, surface transformation',
    color: '#F97316',
    description: 'Video projected onto 3D surfaces',
  },
  {
    id: 'sfp6',
    name: 'Nanosecond Exposures',
    category: 'Special Effects',
    promptKeyword: 'nanosecond exposures, ultra high-speed, split-second capture',
    color: '#F97316',
    description: 'Ultra-high-speed photography',
  },
  {
    id: 'sfp7',
    name: 'Double Exposure',
    category: 'Special Effects',
    promptKeyword: 'double exposure, layered images, ghostly composite, overlapping',
    color: '#F97316',
    description: 'Multiple images on same frame',
  },
  {
    id: 'sfp8',
    name: 'Smoke Diffusion',
    category: 'Special Effects',
    promptKeyword: 'smoke diffusion, atmospheric haze, volumetric atmosphere, fog',
    color: '#F97316',
    description: 'Atmospheric haze and smoke',
  },
  {
    id: 'sfp9',
    name: 'Lens Flare Artistry',
    category: 'Special Effects',
    promptKeyword: 'lens flare artistry, optical artifacts, light halos, bokeh',
    color: '#F97316',
    description: 'Intentional lens artifacts',
  },

  // ========== SPECIAL EFFECTS: DIGITAL (12 tags) ==========
  {
    id: 'sfd1',
    name: 'Particle Systems',
    category: 'Special Effects',
    promptKeyword: 'particle systems, simulated swarms, dust, sparks, magic particles',
    color: '#FB923C',
    description: 'Simulated particle swarms',
  },
  {
    id: 'sfd2',
    name: 'Holographic Overlay',
    category: 'Special Effects',
    promptKeyword: 'holographic overlay, sci-fi interface, floating displays, HUD',
    color: '#FB923C',
    description: 'Sci-fi interface graphics',
  },
  {
    id: 'sfd3',
    name: 'Chromatic Aberration',
    category: 'Special Effects',
    promptKeyword: 'chromatic aberration, color fringing, RGB split, lens imperfection',
    color: '#FB923C',
    description: 'Color fringing and separation',
  },
  {
    id: 'sfd4',
    name: 'Digital Distortion',
    category: 'Special Effects',
    promptKeyword: 'digital distortion, glitch, pixel corruption, data errors',
    color: '#FB923C',
    description: 'Pixel manipulation glitches',
  },
  {
    id: 'sfd5',
    name: 'Wire Removal',
    category: 'Special Effects',
    promptKeyword: 'wire removal, clean plate, invisible rigging, seamless composite',
    color: '#FB923C',
    description: 'Digitally erasing safety wires',
  },
  {
    id: 'sfd6',
    name: 'Motion Capture',
    category: 'Special Effects',
    promptKeyword: 'motion capture, performance tracking, digital character, mocap',
    color: '#FB923C',
    description: 'Actor performance to digital character',
  },
  {
    id: 'sfd7',
    name: 'Miniature Integration',
    category: 'Special Effects',
    promptKeyword: 'miniature integration, scale models, forced perspective, compositing',
    color: '#FB923C',
    description: 'Small-scale model compositing',
  },
  {
    id: 'sfd8',
    name: 'Weather Simulation',
    category: 'Special Effects',
    promptKeyword: 'weather simulation, digital rain, snow, fog, atmospheric effects',
    color: '#FB923C',
    description: 'Digital weather elements',
  },
  {
    id: 'sfd9',
    name: 'Color Grading',
    category: 'Special Effects',
    promptKeyword: 'color grading, color manipulation, mood establishment, cinematic look',
    color: '#FB923C',
    description: 'Sophisticated color manipulation',
  },
  {
    id: 'sfd10',
    name: 'Mixed Media Composite',
    category: 'Special Effects',
    promptKeyword: 'mixed media composite, layered integration, multiple sources, hybrid',
    color: '#FB923C',
    description: 'Combining multiple visual sources',
  },
  {
    id: 'sfd11',
    name: 'Neural Style Transfer',
    category: 'Special Effects',
    promptKeyword: 'neural style transfer, AI artistic style, machine learning, painterly',
    color: '#FB923C',
    description: 'AI-driven artistic style application',
  },
  {
    id: 'sfd12',
    name: 'Pull Back Reveal',
    category: 'Special Effects',
    promptKeyword: 'pull back reveal, dramatic reveal, context surprise, scale revelation',
    color: '#FB923C',
    description: 'Camera pulls back to reveal context',
  },
];
